# Generated by Django 3.0.8 on 2020-07-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='this is the desciption'),
            preserve_default=False,
        ),
    ]
